var _page_settings = {
	'Image 79': ' ..79 - Lorem ipsum dolor sit amet, consectetur adipisicing elit. Esse repudiandae harum obcaecati cupiditate est maxime, asperiores, praesentium libero incidunt molestiae natus modi, omnis doloribus provident nulla magnam quidem nam. Sit ipsam voluptatem cumque facere, inventore, eligendi veritatis perferendis praesentium, error nemo, ex molestias harum. Laudantium excepturi quo consequatur doloribus quae ut velit iusto dolores ipsa.',
	'Image 80': ' .. 80 -- Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laborum, maiores nulla quae aliquid excepturi molestiae, atque assumenda officia saepe, quod deserunt corporis optio quas neque doloremque, totam possimus suscipit praesentium pariatur at alias numquam quibusdam deleniti! Molestiae repellendus adipisci eaque hic laudantium sequi iste est temporibus sit omnis. Officia ad ea modi exercitationem, ab quisquam alias. Quibusdam dicta tenetur, optio, molestias similique placeat vel aliquam maxime nesciunt iusto iure saepe non omnis minus quisquam porro voluptatem distinctio quas.',
	'Image 82': ' ..82 -- Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint dicta cum adipisci provident sequi ad nisi cumque labore modi unde alias, maiores earum fugit. Officiis tenetur laboriosam veritatis consequatur rem, neque ipsam velit qui.',
	'Image 83': ' ..83 - Lorem ipsum dolor sit amet, consectetur adipisicing elit. A quam maiores minima esse tenetur, sapiente obcaecati alias nam pariatur quas commodi quia cum, ipsa sit corrupti, incidunt error iusto. Voluptas quidem assumenda hic eaque! Officiis doloremque odio, perspiciatis neque porro modi expedita pariatur, autem eum ab nemo accusantium dolor. Veritatis aliquam autem magni atque corporis magnam, perspiciatis facilis enim consequatur rerum error animi ipsam asperiores, ducimus consectetur est nobis obcaecati facere at eligendi. Possimus repellendus vel error sed labore perspiciatis non illum officia!',
	'Image 84': ' ..83 Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla repellendus libero dolorum atque ab numquam saepe debitis maiores velit praesentium, vitae voluptatibus sit, unde, quae. Nesciunt quos facilis expedita cum, in voluptate fugit perspiciatis sunt repudiandae. Laudantium recusandae aut in.',
	'Image 85': ' ..85 - Lorem ipsum dolor sit amet, consectetur adipisicing elit. Esse repudiandae harum obcaecati cupiditate est maxime, asperiores, praesentium libero incidunt molestiae natus modi, omnis doloribus provident nulla magnam quidem nam. Sit ipsam voluptatem cumque facere, inventore, eligendi veritatis perferendis praesentium, error nemo, ex molestias harum. Laudantium excepturi quo consequatur doloribus quae ut velit iusto dolores ipsa. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsa accusamus esse maxime atque aliquam cum assumenda minima dolorem odio id nobis, dignissimos!'
};

settings.init(_page_settings);